<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store, private');
function reply(array $p,int $s=200):never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function b64d(string $v):string|false{$n=strtr($v,'-_','+/');$n.=str_repeat('=',(4-strlen($n)%4)%4);return base64_decode($n,true);}
function authenticated(string $email,string $secret):bool{$t=(string)($_COOKIE['cs_jornada_admin']??'');$p=explode('.',$t);if(count($p)!==2)return false;$sig=rtrim(strtr(base64_encode(hash_hmac('sha256',$p[0],$secret,true)),'+/','-_'),'=');if(!hash_equals($sig,$p[1]))return false;$raw=b64d($p[0]);$d=is_string($raw)?json_decode($raw,true):null;return is_array($d)&&strtolower((string)($d['email']??''))===strtolower($email)&&(int)($d['exp']??0)>time();}
function api(string $url,string $key):array{$c=curl_init($url);if(!$c)return ['ok'=>false,'data'=>[]];curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>['Accept: application/json','Content-Type: application/json','User-Agent: ConexaoSeresJornadaAdmin/1.0','access_token: '.$key]]);$raw=curl_exec($c);$status=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);$err=curl_errno($c);curl_close($c);$d=is_string($raw)?json_decode($raw,true):null;return ['ok'=>$err===0&&$status>=200&&$status<300,'data'=>is_array($d)?$d:[]];}
function paid(string $s):bool{return in_array(strtoupper($s),['CONFIRMED','RECEIVED','RECEIVED_IN_CASH'],true);}
if($_SERVER['REQUEST_METHOD']!=='GET')reply(['message'=>'Método não permitido.'],405);
$config=[];$file=__DIR__.'/config.php';if(is_file($file)){$x=require $file;if(is_array($x))$config=$x;}
$email=strtolower(trim((string)($config['jornada_admin_email']??'contato@conexaoseres.com.br')));$secret=trim((string)($config['jornada_admin_session_secret']??''));if(strlen($secret)<32)reply(['message'=>'O acesso administrativo ainda não foi configurado.'],503);if(!authenticated($email,$secret))reply(['message'=>'Sessão não autenticada.'],401);
$key=trim((string)($config['asaas_api_key']??''));$base=rtrim((string)($config['asaas_api_url']??'https://api.asaas.com/v3'),'/');if($key===''||!function_exists('curl_init'))reply(['message'=>'Integração de pagamentos indisponível.'],503);
$payments=[];$offset=0;for($page=0;$page<30;$page++){$r=api($base.'/payments?'.http_build_query(['offset'=>$offset,'limit'=>100,'dateCreated[ge]'=>'2026-09-01']),$key);if(!$r['ok'])reply(['message'=>'Não foi possível consultar as inscrições.'],502);$items=is_array($r['data']['data']??null)?$r['data']['data']:[];foreach($items as $p)if(is_array($p)&&preg_match('/^cs-jornada-yoga-2026-[a-f0-9]{24}$/',trim((string)($p['externalReference']??'')))===1)$payments[]=$p;$offset+=count($items);$total=is_numeric($r['data']['totalCount']??null)?(int)$r['data']['totalCount']:null;if(!$items||(($r['data']['hasMore']??false)!==true&&($total===null||$offset>=$total)))break;}
$cache=[];$rows=[];foreach($payments as $p){$cid=trim((string)($p['customer']??''));if(!array_key_exists($cid,$cache)){$r=$cid!==''?api($base.'/customers/'.rawurlencode($cid),$key):['ok'=>false,'data'=>[]];$cache[$cid]=$r['ok']?$r['data']:[];}$c=$cache[$cid];$status=(string)($p['status']??'');$rows[]=['paymentId'=>(string)($p['id']??''),'customerId'=>$cid,'externalReference'=>(string)($p['externalReference']??''),'name'=>(string)($c['name']??''),'email'=>(string)($c['email']??''),'cpf'=>(string)($c['cpfCnpj']??''),'whatsapp'=>trim((string)($c['mobilePhone']??''))!==''?(string)$c['mobilePhone']:(string)($c['phone']??''),'status'=>$status,'paid'=>paid($status),'billingType'=>(string)($p['billingType']??''),'value'=>(float)($p['value']??297),'dateCreated'=>(string)($p['dateCreated']??''),'dueDate'=>(string)($p['dueDate']??''),'paymentDate'=>(string)($p['paymentDate']??$p['confirmedDate']??$p['clientPaymentDate']??''),'invoiceUrl'=>(string)($p['invoiceUrl']??'')];}
usort($rows,fn($a,$b)=>strcmp($b['dateCreated'],$a['dateCreated']));$paidRows=array_filter($rows,fn($r)=>(bool)$r['paid']);
reply(['eventId'=>'jornada-yoga-2026','adminEmail'=>$email,'registrations'=>$rows,'summary'=>['total'=>count($rows),'paid'=>count($paidRows),'pending'=>count(array_filter($rows,fn($r)=>$r['status']==='PENDING')),'overdue'=>count(array_filter($rows,fn($r)=>$r['status']==='OVERDUE')),'amountPaid'=>array_reduce($paidRows,fn($sum,$r)=>$sum+(float)$r['value'],0.0)]]);
