<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

function reply(array $data,int $status=200):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function digits(string $v):string{return preg_replace('/\D+/','',$v)??'';}
function clean_text(string $v):string{return trim(preg_replace('/\s+/u',' ',$v)??'');}
function valid_cpf(string $v):bool{$c=digits($v);if(strlen($c)!==11||preg_match('/^(\d)\1{10}$/',$c))return false;for($p=9;$p<=10;$p++){$s=0;$f=$p+1;for($i=0;$i<$p;$i++)$s+=(int)$c[$i]*($f-$i);$d=($s*10)%11;if($d===10)$d=0;if($d!==(int)$c[$p])return false;}return true;}
function valid_phone(string $v):bool{$n=digits($v);if(strlen($n)===13&&str_starts_with($n,'55'))$n=substr($n,2);return strlen($n)===11&&$n[2]==='9';}
function national_phone(string $v):string{$n=digits($v);return strlen($n)===13&&str_starts_with($n,'55')?substr($n,2):$n;}
function api(string $method,string $url,string $key,?array $payload=null):array{$c=curl_init($url);if(!$c)return ['ok'=>false,'data'=>[]];$opts=[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>['Accept: application/json','Content-Type: application/json','User-Agent: ConexaoSeresJornadaYoga/1.0','access_token: '.$key]];if($payload!==null)$opts[CURLOPT_POSTFIELDS]=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);curl_setopt_array($c,$opts);$raw=curl_exec($c);$status=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);$error=curl_errno($c);curl_close($c);$parsed=is_string($raw)?json_decode($raw,true):null;return ['ok'=>$error===0&&$status>=200&&$status<300,'data'=>is_array($parsed)?$parsed:[]];}
function customer_list(string $base,string $key,string $field,string $value):?array{$r=api('GET',$base.'/customers?'.http_build_query([$field=>$value,'limit'=>100]),$key);return $r['ok']?(is_array($r['data']['data']??null)?$r['data']['data']:[]):null;}
function customer_ids(array $items):array{$out=[];foreach($items as $i){$id=is_array($i)?trim((string)($i['id']??'')):'';if($id!=='')$out[$id]=true;}return array_keys($out);}
function resolve_customer(array $cpf,array $email):array{$a=customer_ids($cpf);$b=customer_ids($email);$both=array_values(array_intersect($a,$b));if(count($a)>1||count($b)>1)return ['id'=>'','conflict'=>true];if(count($both)===1)return ['id'=>$both[0],'conflict'=>false];if(count($a)===1&&!$b)return ['id'=>$a[0],'conflict'=>false];if(count($b)===1&&!$a)return ['id'=>$b[0],'conflict'=>false];if(!$a&&!$b)return ['id'=>'','conflict'=>false];return ['id'=>'','conflict'=>true];}
function payment_ref(string $cpf):string{return 'cs-jornada-yoga-2026-'.substr(hash('sha256','jornada-yoga-2026:'.digits($cpf)),0,24);}
function customer_ref(string $cpf):string{return 'cs-jornada-cliente-'.substr(hash('sha256','conexao-seres-jornada-cliente:'.digits($cpf)),0,24);}
function due_date():string{$d=new DateTimeImmutable('now',new DateTimeZone('America/Sao_Paulo'));$w=(int)$d->format('N');return $d->modify('+'.($w===5?3:($w===6?2:1)).' day')->format('Y-m-d');}
function find_payment(string $base,string $key,string $ref):array{$r=api('GET',$base.'/payments?'.http_build_query(['externalReference'=>$ref,'limit'=>10]),$key);if(!$r['ok'])return ['ok'=>false,'payment'=>null];foreach(($r['data']['data']??[]) as $p)if(is_array($p)&&($p['externalReference']??'')===$ref)return ['ok'=>true,'payment'=>$p];return ['ok'=>true,'payment'=>null];}
function verify_turnstile(string $secret,string $token,string $hostname):bool{$c=curl_init('https://challenges.cloudflare.com/turnstile/v0/siteverify');if(!$c)return false;curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>8,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode(['secret'=>$secret,'response'=>$token])]);$raw=curl_exec($c);$status=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);$data=is_string($raw)?json_decode($raw,true):null;return $status>=200&&$status<300&&is_array($data)&&($data['success']??false)===true&&($data['action']??'')==='jornada_yoga'&&($hostname===''||($data['hostname']??'')===$hostname);}
function payment_payload(array $p,bool $existing,bool $customer):array{return ['success'=>true,'eventId'=>'jornada-yoga-2026','paymentId'=>(string)($p['id']??''),'invoiceUrl'=>(string)($p['invoiceUrl']??''),'status'=>(string)($p['status']??'PENDING'),'value'=>297,'existingRegistration'=>$existing,'existingCustomer'=>$customer];}

if($_SERVER['REQUEST_METHOD']!=='POST')reply(['message'=>'Método não permitido.'],405);
$config=[];$file=__DIR__.'/config.php';if(is_file($file)){$loaded=require $file;if(is_array($loaded))$config=$loaded;}
$body=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($body))reply(['message'=>'Dados inválidos.'],400);
$name=clean_text((string)($body['name']??''));$cpf=digits((string)($body['cpf']??''));$email=strtolower(trim((string)($body['email']??'')));$phone=national_phone((string)($body['whatsapp']??''));$turnstile=trim((string)($body['turnstileToken']??''));
if(mb_strlen($name)<5||count(preg_split('/\s+/u',$name)?:[])<2||!valid_cpf($cpf)||filter_var($email,FILTER_VALIDATE_EMAIL)===false||!valid_phone($phone)||($body['consent']??false)!==true||(string)($body['website']??'')!==''||$turnstile==='')reply(['message'=>'Confira os dados informados e tente novamente.'],400);
$key=trim((string)($config['asaas_api_key']??''));$base=rtrim((string)($config['asaas_api_url']??'https://api.asaas.com/v3'),'/');$secret=trim((string)($config['turnstile_secret_key']??''));$hostname=trim((string)($config['turnstile_expected_hostname']??''));
if($key===''||$secret===''||!function_exists('curl_init'))reply(['message'=>'As inscrições estão temporariamente indisponíveis.'],503);
if(!verify_turnstile($secret,$turnstile,$hostname))reply(['message'=>'Não foi possível confirmar a verificação de segurança.'],400);
$ref=payment_ref($cpf);$found=find_payment($base,$key,$ref);if(!$found['ok'])reply(['message'=>'Não conseguimos confirmar sua inscrição agora.'],502);if(is_array($found['payment']))reply(payment_payload($found['payment'],true,true));
$cpfMatches=customer_list($base,$key,'cpfCnpj',$cpf);$emailMatches=customer_list($base,$key,'email',$email);if($cpfMatches===null||$emailMatches===null)reply(['message'=>'Não conseguimos consultar seu cadastro agora.'],502);$resolved=resolve_customer($cpfMatches,$emailMatches);if($resolved['conflict'])reply(['message'=>'Encontramos mais de um cadastro relacionado aos dados informados. Entre em contato com a Conexão Seres.'],409);
$customer=(string)$resolved['id'];$existingCustomer=$customer!=='';if(!$customer){$created=api('POST',$base.'/customers',$key,['name'=>$name,'cpfCnpj'=>$cpf,'email'=>$email,'mobilePhone'=>$phone,'externalReference'=>customer_ref($cpf),'notificationDisabled'=>false]);$customer=trim((string)($created['data']['id']??''));if(!$created['ok']||$customer==='')reply(['message'=>'Não conseguimos concluir seu cadastro agora.'],502);}
$charge=find_payment($base,$key,$ref);if(!$charge['ok'])reply(['message'=>'Não conseguimos gerar a cobrança agora.'],502);$createdPayment=false;
if(!is_array($charge['payment'])){$made=api('POST',$base.'/payments',$key,['customer'=>$customer,'billingType'=>'UNDEFINED','value'=>297,'dueDate'=>due_date(),'description'=>'Jornada de Expansão Mental e Corporal — 8 encontros online, de 07/10/2026 a 25/11/2026.','externalReference'=>$ref]);if($made['ok']&&trim((string)($made['data']['id']??''))!==''){$charge['payment']=$made['data'];$createdPayment=true;}else{$reconcile=find_payment($base,$key,$ref);if(!$reconcile['ok']||!is_array($reconcile['payment']))reply(['message'=>'Não conseguimos gerar a cobrança da Jornada agora.'],502);$charge['payment']=$reconcile['payment'];}}
reply(payment_payload($charge['payment'],!$createdPayment,$existingCustomer),$createdPayment?201:200);
