import { env } from "cloudflare:workers";
import { JORNADA_YOGA_AMOUNT,JORNADA_YOGA_REFERENCE_PATTERN,isPaidJourneyStatus } from "../../../../../lib/jornada-yoga";
import { isJourneyAdminAuthenticated,noStoreJson } from "../../../../../lib/jornada-admin-server";
export const runtime="edge";
type Obj=Record<string,unknown>;type Payment={id?:string;customer?:string;externalReference?:string;invoiceUrl?:string;status?:string;value?:number;billingType?:string;dateCreated?:string;dueDate?:string;paymentDate?:string;confirmedDate?:string;clientPaymentDate?:string};type Customer={id?:string;name?:string;email?:string;cpfCnpj?:string;mobilePhone?:string;phone?:string};
const headers=(key:string)=>({accept:"application/json","content-type":"application/json","user-agent":"ConexaoSeresJornadaAdmin/1.0",access_token:key});
async function get(url:string,key:string,signal:AbortSignal){const r=await fetch(url,{headers:headers(key),signal});if(!r.ok)return {ok:false,data:{} as Obj};const p=await r.json() as unknown;return {ok:true,data:p&&typeof p==="object"&&!Array.isArray(p)?p as Obj:{}};}
const items=<T,>(d:Obj)=>Array.isArray(d.data)?d.data.filter(x=>x&&typeof x==="object") as T[]:[];
async function listPayments(base:string,key:string,signal:AbortSignal){const found:Payment[]=[];let offset=0;for(let page=0;page<30;page++){const u=new URL(base+"/payments");u.searchParams.set("offset",String(offset));u.searchParams.set("limit","100");u.searchParams.set("dateCreated[ge]","2026-09-01");const r=await get(u.toString(),key,signal);if(!r.ok)return null;const pageItems=items<Payment>(r.data);found.push(...pageItems.filter(p=>typeof p.externalReference==="string"&&JORNADA_YOGA_REFERENCE_PATTERN.test(p.externalReference.trim())));offset+=pageItems.length;const total=typeof r.data.totalCount==="number"?r.data.totalCount:null;if(!pageItems.length||(r.data.hasMore!==true&&(total===null||offset>=total)))break;}return found;}
export async function GET(request:Request){
 const auth=await isJourneyAdminAuthenticated(request);if(!auth.configured)return noStoreJson({message:"O acesso administrativo ainda não foi configurado."},{status:503});if(!auth.authenticated)return noStoreJson({message:"Sessão não autenticada."},{status:401});
 const key=(env.ASAAS_API_KEY as string|undefined)?.trim()||"";const base=((env.ASAAS_API_URL as string|undefined)||"https://api.asaas.com/v3").replace(/\/$/,"");if(!key)return noStoreJson({message:"Integração de pagamentos indisponível."},{status:503});
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),45000);
 try{const payments=await listPayments(base,key,controller.signal);if(!payments)return noStoreJson({message:"Não foi possível consultar as inscrições."},{status:502});
 const ids=Array.from(new Set(payments.map(p=>p.customer?.trim()||"").filter(Boolean)));const customers=new Map<string,Customer>();
 for(let i=0;i<ids.length;i+=8){const batch=await Promise.all(ids.slice(i,i+8).map(async id=>({id,r:await get(base+"/customers/"+encodeURIComponent(id),key,controller.signal)})));for(const x of batch)if(x.r.ok)customers.set(x.id,x.r.data as Customer);}
 const registrations=payments.map(p=>{const customerId=p.customer?.trim()||"",c=customers.get(customerId),status=p.status||"";return {paymentId:p.id||"",customerId,externalReference:p.externalReference||"",name:c?.name||"",email:c?.email||"",cpf:c?.cpfCnpj||"",whatsapp:c?.mobilePhone?.trim()||c?.phone||"",status,paid:isPaidJourneyStatus(status),billingType:p.billingType||"",value:typeof p.value==="number"?p.value:Number(p.value||JORNADA_YOGA_AMOUNT),dateCreated:p.dateCreated||"",dueDate:p.dueDate||"",paymentDate:p.paymentDate||p.confirmedDate||p.clientPaymentDate||"",invoiceUrl:p.invoiceUrl||""};}).sort((a,b)=>b.dateCreated.localeCompare(a.dateCreated));
 return noStoreJson({eventId:"jornada-yoga-2026",adminEmail:auth.config.email,registrations,summary:{total:registrations.length,paid:registrations.filter(x=>x.paid).length,pending:registrations.filter(x=>x.status==="PENDING").length,overdue:registrations.filter(x=>x.status==="OVERDUE").length,amountPaid:registrations.filter(x=>x.paid).reduce((s,x)=>s+x.value,0)}});
 }catch(error){console.error("Journey admin list failed",{timedOut:error instanceof Error&&error.name==="AbortError"});return noStoreJson({message:"Não foi possível consultar as inscrições agora."},{status:502});}finally{clearTimeout(timeout);}
}