"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { CheckCircle2,Download,ExternalLink,KeyRound,Loader2,LogOut,RefreshCw,Search,Users,WalletCards } from "lucide-react";
import { AppVersion } from "@/components/layout/AppVersion";
import { formatCpf,formatCurrency,formatWhatsapp,jornadaBillingTypeLabel,jornadaPaymentStatusLabel } from "@/lib/jornada-yoga";

const LOGO="https://conexaoseres.com.br/wp-content/uploads/2024/04/LOGOTIPO-CONEXAO-SERES-HORIZONTAL-TRANSPARENTE.png";
type Row={paymentId:string;customerId:string;name:string;email:string;cpf:string;whatsapp:string;status:string;paid:boolean;billingType:string;value:number;dateCreated:string;paymentDate:string;invoiceUrl:string};
type Data={adminEmail?:string;registrations?:Row[];summary?:{total:number;paid:number;pending:number;overdue:number;amountPaid:number};message?:string};
const date=(v:string)=>{const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v);return !v?"—":m?`${m[3]}/${m[2]}/${m[1]}`:v;};
const csv=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;

export function JornadaYogaAdminPage(){
 const [email,setEmail]=useState("contato@conexaoseres.com.br"),[password,setPassword]=useState(""),[auth,setAuth]=useState<boolean|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[data,setData]=useState<Data|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL");
 useEffect(()=>{document.title="Inscritos da Jornada | Conexão Seres";void load();},[]);
 async function load(){setLoading(true);setMessage("");try{const r=await fetch("/api/jornada-yoga/admin/registrations",{cache:"no-store"});const p=await r.json() as Data;if(r.status===401){setAuth(false);setData(null);return;}if(!r.ok){setMessage(p.message||"Não foi possível carregar os inscritos.");return;}setAuth(true);setData(p);}catch{setMessage("Não foi possível carregar os inscritos.");}finally{setLoading(false);}}
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const r=await fetch("/api/jornada-yoga/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const p=await r.json() as {success?:boolean;message?:string};if(!r.ok||!p.success){setMessage(p.message||"Não foi possível entrar.");setAuth(false);return;}setPassword("");await load();}catch{setMessage("Não foi possível entrar.");setAuth(false);}finally{setLoading(false);}}
 async function logout(){await fetch("/api/jornada-yoga/admin/logout",{method:"POST"});setAuth(false);setData(null);}
 const rows=useMemo(()=>{const n=query.trim().toLowerCase();return(data?.registrations||[]).filter(r=>(filter==="ALL"||(filter==="PAID"&&r.paid)||(filter==="PENDING"&&r.status==="PENDING")||(filter==="OVERDUE"&&r.status==="OVERDUE"))&&(!n||[r.name,r.email,r.cpf,r.whatsapp,r.paymentId].join(" ").toLowerCase().includes(n)));},[data,query,filter]);
 function exportCsv(){const header=["Nome","CPF","E-mail","WhatsApp","Data de inscrição","Status","Forma de pagamento","Data do pagamento","Valor","ID cobrança"];const body=rows.map(r=>[r.name,formatCpf(r.cpf),r.email,formatWhatsapp(r.whatsapp),date(r.dateCreated),jornadaPaymentStatusLabel(r.status),jornadaBillingTypeLabel(r.billingType),date(r.paymentDate),r.value.toFixed(2).replace(".",","),r.paymentId]);const blob=new Blob(["\ufeff"+[header,...body].map(row=>row.map(csv).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="inscritos-jornada-yoga.csv";a.click();URL.revokeObjectURL(url);}
 if(auth!==true)return <main className="grid min-h-screen place-items-center bg-[#f8f5ec] px-5"><div className="w-full max-w-md rounded-2xl border border-[#d5ded1] bg-white p-7 shadow-sm"><img src={LOGO} alt="Conexão Seres" className="mx-auto w-[220px]"/><h1 className="mt-7 text-center text-2xl font-semibold text-[#005000]">Inscritos da Jornada</h1><p className="mt-2 text-center text-sm text-[#687264]">Acesso restrito à equipe da Conexão Seres.</p><form onSubmit={login} className="mt-7 space-y-4"><label className="block"><span className="mb-2 block text-sm font-semibold">E-mail</span><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="h-12 w-full rounded-lg border border-[#cfd6ca] px-3"/></label><label className="block"><span className="mb-2 block text-sm font-semibold">Senha</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-lg border border-[#cfd6ca] px-3"/></label>{message&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>}<button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#005000] font-semibold text-white">{loading?<Loader2 className="size-5 animate-spin"/>:<KeyRound className="size-5"/>}Entrar</button></form><p className="mt-5 text-center text-xs text-[#8a9186]"><AppVersion/></p></div></main>;
 const s=data?.summary||{total:0,paid:0,pending:0,overdue:0,amountPaid:0};
 return <main className="min-h-screen bg-[#f6f7f5]"><header className="border-b bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 sm:px-8"><img src={LOGO} className="w-[185px]" alt="Conexão Seres"/><button onClick={logout} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><LogOut className="size-4"/>Sair</button></div></header>
 <div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#8a5a18]">Administração</p><h1 className="mt-2 text-3xl font-semibold text-[#005000]">Inscritos na Jornada</h1><p className="mt-2 text-sm text-[#687264]">Consulta sincronizada com as cobranças da Jornada no Asaas.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2.5 text-sm font-semibold"><RefreshCw className="size-4"/>Atualizar</button><button onClick={exportCsv} disabled={!rows.length} className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Download className="size-4"/>CSV</button></div></div>
 {message&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
  {label:"Inscrições",value:String(s.total),Icon:Users},
  {label:"Pagas",value:String(s.paid),Icon:CheckCircle2},
  {label:"Pendentes",value:String(s.pending),Icon:WalletCards},
  {label:"Vencidas",value:String(s.overdue),Icon:RefreshCw},
  {label:"Recebido",value:formatCurrency(s.amountPaid),Icon:CheckCircle2},
].map(({label,value,Icon})=><div key={label} className="rounded-xl border bg-white p-4"><div className="flex justify-between text-xs font-semibold uppercase text-[#737c70]"><span>{label}</span><Icon className="size-4"/></div><p className="mt-3 text-2xl font-semibold text-[#315f31]">{value}</p></div>)}</section>
 <section className="mt-6 overflow-hidden rounded-xl border bg-white"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 size-4 text-[#8c9389]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome, CPF, e-mail ou WhatsApp" className="h-11 w-full rounded-lg border pl-10 pr-3"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="h-11 rounded-lg border px-3"><option value="ALL">Todos</option><option value="PAID">Pagos</option><option value="PENDING">Pendentes</option><option value="OVERDUE">Vencidos</option></select></div>
 <div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead className="bg-[#f8faf7] text-xs uppercase text-[#737c70]"><tr>{["Inscrito","Contato","Inscrição","Pagamento","Status","Valor","Cobrança"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.paymentId}><td className="px-4 py-4"><b className="text-[#315f31]">{r.name||"—"}</b><p className="mt-1 text-xs text-[#7c8479]">{r.cpf?formatCpf(r.cpf):"—"}</p></td><td className="px-4 py-4">{r.email||"—"}<p className="mt-1 text-xs">{r.whatsapp?formatWhatsapp(r.whatsapp):"—"}</p></td><td className="px-4 py-4">{date(r.dateCreated)}</td><td className="px-4 py-4">{jornadaBillingTypeLabel(r.billingType)}<p className="mt-1 text-xs">{r.paymentDate?date(r.paymentDate):"Ainda não pago"}</p></td><td className="px-4 py-4">{jornadaPaymentStatusLabel(r.status)}</td><td className="px-4 py-4 font-semibold">{formatCurrency(r.value)}</td><td className="px-4 py-4">{r.invoiceUrl?<a href={r.invoiceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-[#8a5a18]">Abrir <ExternalLink className="size-3"/></a>:"—"}</td></tr>)}{!rows.length&&<tr><td colSpan={7} className="p-10 text-center text-[#7c8479]">Nenhum inscrito encontrado.</td></tr>}</tbody></table></div><div className="border-t px-4 py-3 text-xs text-[#7c8479]">Exibindo {rows.length} de {data?.registrations?.length||0} · <AppVersion/></div></section></div></main>;
}
